== Get the latest release of the book

The quickest way to start reading right now is to view the PDF version here:

https://github.com/thoughtbot/backbone-js-on-rails/raw/master/release/book.pdf

The book is currently available in the following formats:

* PDF: release/book.pdf
* Multi-page HTML: release/index.html
* Single-page HTML: release/book.html
* Mobi (Kindle): release/book.mobi

For HTML versions, clone the repository and look at the HTML so that images
and other assets are properly loaded.

== Instructions for authors

==== Note: Readers of the book don't need to worry about the instructions below.

This book is written using using the git-scribe toolchain, which can be found at:

http://github.com/schacon/git-scribe

Instructions on how to install the tool and use it for things like editing this
book, submitting errata and providing translations can be found at that site.

=== Dependencies

Install dependencies with Bundler:

  bundle install

Now install the git-scribe dependencies:

==== Installing git-scribe dependencies on OSX

  brew install https://raw.github.com/adamv/homebrew-alt/master/non-free/kindlegen.rb
  brew install asciidoc fop source-highlight docbook

Make sure you register docbook after installation:

  sudo docbook-register

And add the following to your ~/.bashrc or equivalent (as per `brew info docbook`):

  export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"

==== Installing git-scribe dependencies on Ubuntu

   sudo aptitude install asciidoc fop source-highlight docbook

Install KindleGen into ~/bin; you can put it anywhere in your PATH you like:

   wget -P /tmp/ http://s3.amazonaws.com/kindlegen/kindlegen_linux_2.6_i386_v1.2.tar.gz
   tar -C /tmp/ -xzf /tmp/kindlegen_linux_2.6_i386_v1.2.tar.gz
   mv /tmp/kindlegen ~/bin/

=== Verifying the install

Check to see that everything is working together:

  git scribe check

== Writing

Run +guard+ to watch the +book/+ directory and automatically rebuild the SITE
target when anything changes:

  $ bundle exec guard
  Guard is now watching at '/Users/jason/dev/backbone-js-on-rails'
  git-scribe is waiting for book changes...
  git-scribe is generating a new SITE from the book...
  git-scribe successfully generated a new SITE.

You can now see the site in +output/index.html+.

== Releasing

Run +rake release+ to build all output targets, commit to git, and push up to
GitHub.
