source 'http://rubygems.org'

gem 'rails', '3.2.6'
gem 'sqlite3', '~> 1.3.5'

gem 'rails-backbone', '~> 0.7.0'
gem 'jquery-rails'
gem 'ejs'
gem "flutie", "~> 1.3.2"
gem "clearance", "~> 0.13.0"
gem 'paperclip'
gem 'rabl'
gem 'backbone-support', :path => "~/dev/backbone-support"

group :assets do
  gem "sass-rails", "~> 3.2.0"
  gem 'coffee-rails', "~> 3.2.0"
  gem 'uglifier'
end

group :development, :test do
  gem "rspec-rails", "~> 2.9.0"
  gem "ruby-debug19"
  gem 'jasmine', :git => "git://github.com/pivotal/jasmine-gem.git", 
                 :ref => "34c1529c3f7"
  gem 'cucumber-rails', "~> 1.0.2", :require => false
end

group :test do
  gem 'turn', :require => false
  gem "capybara", "~> 1.1.1"
  gem 'selenium-webdriver', '~> 2.18.0'
  gem "factory_girl_rails", "~> 3.4.0"
  gem "bourne"
  gem "database_cleaner"
  gem "nokogiri"
  gem "shoulda-matchers"
  gem "launchy"
  gem "guard-spork"
  gem "spork", "~> 0.9.0.rc"
end
